PARTIDOS = [
    # GRUPO A (ids 1-6)
    {"id": 1, "grupo": "Grupo A", "local": "México", "visitante": "Sudáfrica", "fecha": "11 Junio", "hora": "15:00", "estadio": "Estadio Azteca", "visto": 0},
    {"id": 2, "grupo": "Grupo A", "local": "Argentina", "visitante": "Nigeria", "fecha": "12 Junio", "hora": "18:00", "estadio": "Estadio Akron", "visto": 0},
    {"id": 3, "grupo": "Grupo A", "local": "México", "visitante": "Argentina", "fecha": "16 Junio", "hora": "20:00", "estadio": "Estadio Azteca", "visto": 0},
    {"id": 4, "grupo": "Grupo A", "local": "Sudáfrica", "visitante": "Nigeria", "fecha": "17 Junio", "hora": "15:00", "estadio": "Estadio Akron", "visto": 0},
    {"id": 5, "grupo": "Grupo A", "local": "México", "visitante": "Nigeria", "fecha": "21 Junio", "hora": "18:00", "estadio": "Estadio Azteca", "visto": 0},
    {"id": 6, "grupo": "Grupo A", "local": "Sudáfrica", "visitante": "Argentina", "fecha": "21 Junio", "hora": "18:00", "estadio": "Estadio Akron", "visto": 0},
    # GRUPO B (ids 7-12)
    {"id": 7, "grupo": "Grupo B", "local": "Brasil", "visitante": "Costa Rica", "fecha": "12 Junio", "hora": "13:00", "estadio": "Estadio Corregidora", "visto": 0},
    {"id": 8, "grupo": "Grupo B", "local": "Alemania", "visitante": "Marruecos", "fecha": "13 Junio", "hora": "18:00", "estadio": "Estadio BBVA", "visto": 0},
    {"id": 9, "grupo": "Grupo B", "local": "Brasil", "visitante": "Alemania", "fecha": "17 Junio", "hora": "20:00", "estadio": "Estadio Corregidora", "visto": 0},
    {"id": 10, "grupo": "Grupo B", "local": "Costa Rica", "visitante": "Marruecos", "fecha": "18 Junio", "hora": "15:00", "estadio": "Estadio BBVA", "visto": 0},
    {"id": 11, "grupo": "Grupo B", "local": "Brasil", "visitante": "Marruecos", "fecha": "22 Junio", "hora": "18:00", "estadio": "Estadio Corregidora", "visto": 0},
    {"id": 12, "grupo": "Grupo B", "local": "Costa Rica", "visitante": "Alemania", "fecha": "22 Junio", "hora": "18:00", "estadio": "Estadio BBVA", "visto": 0},
    # GRUPO C (ids 13-18)
    {"id": 13, "grupo": "Grupo C", "local": "Francia", "visitante": "Australia", "fecha": "13 Junio", "hora": "13:00", "estadio": "Estadio Cuauhtémoc", "visto": 0},
    {"id": 14, "grupo": "Grupo C", "local": "Inglaterra", "visitante": "Senegal", "fecha": "14 Junio", "hora": "18:00", "estadio": "Estadio Universitario", "visto": 0},
    {"id": 15, "grupo": "Grupo C", "local": "Francia", "visitante": "Inglaterra", "fecha": "18 Junio", "hora": "20:00", "estadio": "Estadio Cuauhtémoc", "visto": 0},
    {"id": 16, "grupo": "Grupo C", "local": "Australia", "visitante": "Senegal", "fecha": "19 Junio", "hora": "15:00", "estadio": "Estadio Universitario", "visto": 0},
    {"id": 17, "grupo": "Grupo C", "local": "Francia", "visitante": "Senegal", "fecha": "23 Junio", "hora": "18:00", "estadio": "Estadio Cuauhtémoc", "visto": 0},
    {"id": 18, "grupo": "Grupo C", "local": "Australia", "visitante": "Inglaterra", "fecha": "23 Junio", "hora": "18:00", "estadio": "Estadio Universitario", "visto": 0},
    # GRUPO D (ids 19-24)
    {"id": 19, "grupo": "Grupo D", "local": "España", "visitante": "Japón", "fecha": "14 Junio", "hora": "13:00", "estadio": "Estadio León", "visto": 0},
    {"id": 20, "grupo": "Grupo D", "local": "Países Bajos", "visitante": "Canadá", "fecha": "15 Junio", "hora": "18:00", "estadio": "Estadio Victoria", "visto": 0},
    {"id": 21, "grupo": "Grupo D", "local": "España", "visitante": "Países Bajos", "fecha": "19 Junio", "hora": "20:00", "estadio": "Estadio León", "visto": 0},
    {"id": 22, "grupo": "Grupo D", "local": "Japón", "visitante": "Canadá", "fecha": "20 Junio", "hora": "15:00", "estadio": "Estadio Victoria", "visto": 0},
    {"id": 23, "grupo": "Grupo D", "local": "España", "visitante": "Canadá", "fecha": "24 Junio", "hora": "18:00", "estadio": "Estadio León", "visto": 0},
    {"id": 24, "grupo": "Grupo D", "local": "Japón", "visitante": "Países Bajos", "fecha": "24 Junio", "hora": "18:00", "estadio": "Estadio Victoria", "visto": 0},
    # GRUPO E (ids 25-30)
    {"id": 25, "grupo": "Grupo E", "local": "Italia", "visitante": "Corea del Sur", "fecha": "15 Junio", "hora": "13:00", "estadio": "Estadio Caliente", "visto": 0},
    {"id": 26, "grupo": "Grupo E", "local": "Portugal", "visitante": "Ghana", "fecha": "16 Junio", "hora": "18:00", "estadio": "Estadio Morelos", "visto": 0},
    {"id": 27, "grupo": "Grupo E", "local": "Italia", "visitante": "Portugal", "fecha": "20 Junio", "hora": "20:00", "estadio": "Estadio Caliente", "visto": 0},
    {"id": 28, "grupo": "Grupo E", "local": "Corea del Sur", "visitante": "Ghana", "fecha": "21 Junio", "hora": "15:00", "estadio": "Estadio Morelos", "visto": 0},
    {"id": 29, "grupo": "Grupo E", "local": "Italia", "visitante": "Ghana", "fecha": "25 Junio", "hora": "18:00", "estadio": "Estadio Caliente", "visto": 0},
    {"id": 30, "grupo": "Grupo E", "local": "Corea del Sur", "visitante": "Portugal", "fecha": "25 Junio", "hora": "18:00", "estadio": "Estadio Morelos", "visto": 0},
    # GRUPO F (ids 31-36)
    {"id": 31, "grupo": "Grupo F", "local": "Uruguay", "visitante": "Irán", "fecha": "16 Junio", "hora": "13:00", "estadio": "Estadio Nemesio Díez", "visto": 0},
    {"id": 32, "grupo": "Grupo F", "local": "Croacia", "visitante": "Estados Unidos", "fecha": "17 Junio", "hora": "18:00", "estadio": "Estadio Jalisco", "visto": 0},
    {"id": 33, "grupo": "Grupo F", "local": "Uruguay", "visitante": "Croacia", "fecha": "21 Junio", "hora": "20:00", "estadio": "Estadio Nemesio Díez", "visto": 0},
    {"id": 34, "grupo": "Grupo F", "local": "Irán", "visitante": "Estados Unidos", "fecha": "22 Junio", "hora": "15:00", "estadio": "Estadio Jalisco", "visto": 0},
    {"id": 35, "grupo": "Grupo F", "local": "Uruguay", "visitante": "Estados Unidos", "fecha": "26 Junio", "hora": "18:00", "estadio": "Estadio Nemesio Díez", "visto": 0},
    {"id": 36, "grupo": "Grupo F", "local": "Irán", "visitante": "Croacia", "fecha": "26 Junio", "hora": "18:00", "estadio": "Estadio Jalisco", "visto": 0},
    # GRUPO G (ids 37-42)
    {"id": 37, "grupo": "Grupo G", "local": "Bélgica", "visitante": "Colombia", "fecha": "17 Junio", "hora": "13:00", "estadio": "Estadio Olímpico Universitario", "visto": 0},
    {"id": 38, "grupo": "Grupo G", "local": "Suiza", "visitante": "Ecuador", "fecha": "18 Junio", "hora": "18:00", "estadio": "Estadio Hidalgo", "visto": 0},
    {"id": 39, "grupo": "Grupo G", "local": "Bélgica", "visitante": "Suiza", "fecha": "22 Junio", "hora": "20:00", "estadio": "Estadio Olímpico Universitario", "visto": 0},
    {"id": 40, "grupo": "Grupo G", "local": "Colombia", "visitante": "Ecuador", "fecha": "23 Junio", "hora": "15:00", "estadio": "Estadio Hidalgo", "visto": 0},
    {"id": 41, "grupo": "Grupo G", "local": "Bélgica", "visitante": "Ecuador", "fecha": "27 Junio", "hora": "18:00", "estadio": "Estadio Olímpico Universitario", "visto": 0},
    {"id": 42, "grupo": "Grupo G", "local": "Colombia", "visitante": "Suiza", "fecha": "27 Junio", "hora": "18:00", "estadio": "Estadio Hidalgo", "visto": 0},
    # GRUPO H (ids 43-48)
    {"id": 43, "grupo": "Grupo H", "local": "Chile", "visitante": "Polonia", "fecha": "18 Junio", "hora": "13:00", "estadio": "Estadio Universitario Nuevo León", "visto": 0},
    {"id": 44, "grupo": "Grupo H", "local": "Dinamarca", "visitante": "Perú", "fecha": "19 Junio", "hora": "18:00", "estadio": "Estadio TSM", "visto": 0},
    {"id": 45, "grupo": "Grupo H", "local": "Chile", "visitante": "Dinamarca", "fecha": "23 Junio", "hora": "20:00", "estadio": "Estadio Universitario Nuevo León", "visto": 0},
    {"id": 46, "grupo": "Grupo H", "local": "Polonia", "visitante": "Perú", "fecha": "24 Junio", "hora": "15:00", "estadio": "Estadio TSM", "visto": 0},
    {"id": 47, "grupo": "Grupo H", "local": "Chile", "visitante": "Perú", "fecha": "28 Junio", "hora": "18:00", "estadio": "Estadio Universitario Nuevo León", "visto": 0},
    {"id": 48, "grupo": "Grupo H", "local": "Polonia", "visitante": "Dinamarca", "fecha": "28 Junio", "hora": "18:00", "estadio": "Estadio TSM", "visto": 0},
    # GRUPO I (ids 49-54)
    {"id": 49, "grupo": "Grupo I", "local": "Costa de Marfil", "visitante": "Serbia", "fecha": "19 Junio", "hora": "13:00", "estadio": "Estadio Carlos González", "visto": 0},
    {"id": 50, "grupo": "Grupo I", "local": "Suecia", "visitante": "Paraguay", "fecha": "20 Junio", "hora": "18:00", "estadio": "Estadio Olímpico Benito Juárez", "visto": 0},
    {"id": 51, "grupo": "Grupo I", "local": "Costa de Marfil", "visitante": "Suecia", "fecha": "24 Junio", "hora": "20:00", "estadio": "Estadio Carlos González", "visto": 0},
    {"id": 52, "grupo": "Grupo I", "local": "Serbia", "visitante": "Paraguay", "fecha": "25 Junio", "hora": "15:00", "estadio": "Estadio Olímpico Benito Juárez", "visto": 0},
    {"id": 53, "grupo": "Grupo I", "local": "Costa de Marfil", "visitante": "Paraguay", "fecha": "29 Junio", "hora": "18:00", "estadio": "Estadio Carlos González", "visto": 0},
    {"id": 54, "grupo": "Grupo I", "local": "Serbia", "visitante": "Suecia", "fecha": "29 Junio", "hora": "18:00", "estadio": "Estadio Olímpico Benito Juárez", "visto": 0},
    # GRUPO J (ids 55-60)
    {"id": 55, "grupo": "Grupo J", "local": "Rusia", "visitante": "Túnez", "fecha": "20 Junio", "hora": "13:00", "estadio": "Estadio Luis Pirata Fuente", "visto": 0},
    {"id": 56, "grupo": "Grupo J", "local": "Austria", "visitante": "Panamá", "fecha": "21 Junio", "hora": "18:00", "estadio": "Estadio Marte R. Gómez", "visto": 0},
    {"id": 57, "grupo": "Grupo J", "local": "Rusia", "visitante": "Austria", "fecha": "25 Junio", "hora": "20:00", "estadio": "Estadio Luis Pirata Fuente", "visto": 0},
    {"id": 58, "grupo": "Grupo J", "local": "Túnez", "visitante": "Panamá", "fecha": "26 Junio", "hora": "15:00", "estadio": "Estadio Marte R. Gómez", "visto": 0},
    {"id": 59, "grupo": "Grupo J", "local": "Rusia", "visitante": "Panamá", "fecha": "30 Junio", "hora": "18:00", "estadio": "Estadio Luis Pirata Fuente", "visto": 0},
    {"id": 60, "grupo": "Grupo J", "local": "Túnez", "visitante": "Austria", "fecha": "30 Junio", "hora": "18:00", "estadio": "Estadio Marte R. Gómez", "visto": 0},
    # GRUPO K (ids 61-66)
    {"id": 61, "grupo": "Grupo K", "local": "República Checa", "visitante": "Camerún", "fecha": "21 Junio", "hora": "13:00", "estadio": "Estadio Andrés Quintana Roo", "visto": 0},
    {"id": 62, "grupo": "Grupo K", "local": "Grecia", "visitante": "Jamaica", "fecha": "22 Junio", "hora": "18:00", "estadio": "Estadio Hermanos Serdán", "visto": 0},
    {"id": 63, "grupo": "Grupo K", "local": "República Checa", "visitante": "Grecia", "fecha": "26 Junio", "hora": "20:00", "estadio": "Estadio Andrés Quintana Roo", "visto": 0},
    {"id": 64, "grupo": "Grupo K", "local": "Camerún", "visitante": "Jamaica", "fecha": "27 Junio", "hora": "15:00", "estadio": "Estadio Hermanos Serdán", "visto": 0},
    {"id": 65, "grupo": "Grupo K", "local": "República Checa", "visitante": "Jamaica", "fecha": "1 Julio", "hora": "18:00", "estadio": "Estadio Andrés Quintana Roo", "visto": 0},
    {"id": 66, "grupo": "Grupo K", "local": "Camerún", "visitante": "Grecia", "fecha": "1 Julio", "hora": "18:00", "estadio": "Estadio Hermanos Serdán", "visto": 0},
    # GRUPO L (ids 67-72)
    {"id": 67, "grupo": "Grupo L", "local": "Hungría", "visitante": "Arabia Saudita", "fecha": "22 Junio", "hora": "13:00", "estadio": "Estadio Miguel Alemán", "visto": 0},
    {"id": 68, "grupo": "Grupo L", "local": "Argelia", "visitante": "Nueva Zelanda", "fecha": "23 Junio", "hora": "18:00", "estadio": "Estadio Azteca", "visto": 0},
    {"id": 69, "grupo": "Grupo L", "local": "Hungría", "visitante": "Argelia", "fecha": "27 Junio", "hora": "20:00", "estadio": "Estadio Miguel Alemán", "visto": 0},
    {"id": 70, "grupo": "Grupo L", "local": "Arabia Saudita", "visitante": "Nueva Zelanda", "fecha": "28 Junio", "hora": "15:00", "estadio": "Estadio Azteca", "visto": 0},
    {"id": 71, "grupo": "Grupo L", "local": "Hungría", "visitante": "Nueva Zelanda", "fecha": "2 Julio", "hora": "18:00", "estadio": "Estadio Miguel Alemán", "visto": 0},
    {"id": 72, "grupo": "Grupo L", "local": "Arabia Saudita", "visitante": "Argelia", "fecha": "2 Julio", "hora": "18:00", "estadio": "Estadio Azteca", "visto": 0},
         # OCTAVOS DE FINAL (ids 73-80)
    {"id": 73, "grupo": "Octavos", "local": "Ganador Grupo A", "visitante": "2do Grupo B", "fecha": "3 Julio", "hora": "12:00", "estadio": "Estadio Azteca", "visto": 0},
    {"id": 74, "grupo": "Octavos", "local": "Ganador Grupo C", "visitante": "2do Grupo D", "fecha": "3 Julio", "hora": "16:00", "estadio": "Estadio Akron", "visto": 0},
    {"id": 75, "grupo": "Octavos", "local": "Ganador Grupo E", "visitante": "2do Grupo F", "fecha": "4 Julio", "hora": "12:00", "estadio": "Estadio BBVA", "visto": 0},
    {"id": 76, "grupo": "Octavos", "local": "Ganador Grupo G", "visitante": "2do Grupo H", "fecha": "4 Julio", "hora": "16:00", "estadio": "Estadio Cuauhtémoc", "visto": 0},
    {"id": 77, "grupo": "Octavos", "local": "Ganador Grupo B", "visitante": "2do Grupo A", "fecha": "5 Julio", "hora": "12:00", "estadio": "Estadio León", "visto": 0},
    {"id": 78, "grupo": "Octavos", "local": "Ganador Grupo D", "visitante": "2do Grupo C", "fecha": "5 Julio", "hora": "16:00", "estadio": "Estadio Caliente", "visto": 0},
    {"id": 79, "grupo": "Octavos", "local": "Ganador Grupo F", "visitante": "2do Grupo E", "fecha": "6 Julio", "hora": "12:00", "estadio": "Estadio Olímpico Universitario", "visto": 0},
    {"id": 80, "grupo": "Octavos", "local": "Ganador Grupo H", "visitante": "2do Grupo G", "fecha": "6 Julio", "hora": "16:00", "estadio": "Estadio Jalisco", "visto": 0},
    # CUARTOS DE FINAL (ids 81-84)
    {"id": 81, "grupo": "Cuartos", "local": "Ganador Octavos 1", "visitante": "Ganador Octavos 2", "fecha": "9 Julio", "hora": "13:00", "estadio": "Estadio Azteca", "visto": 0},
    {"id": 82, "grupo": "Cuartos", "local": "Ganador Octavos 3", "visitante": "Ganador Octavos 4", "fecha": "9 Julio", "hora": "17:00", "estadio": "Estadio BBVA", "visto": 0},
    {"id": 83, "grupo": "Cuartos", "local": "Ganador Octavos 5", "visitante": "Ganador Octavos 6", "fecha": "10 Julio", "hora": "13:00", "estadio": "Estadio Akron", "visto": 0},
    {"id": 84, "grupo": "Cuartos", "local": "Ganador Octavos 7", "visitante": "Ganador Octavos 8", "fecha": "10 Julio", "hora": "17:00", "estadio": "Estadio Olímpico Universitario", "visto": 0},
    # SEMIFINALES (ids 85-86)
    {"id": 85, "grupo": "Semifinal", "local": "Ganador Cuartos 1", "visitante": "Ganador Cuartos 2", "fecha": "13 Julio", "hora": "14:00", "estadio": "Estadio Azteca", "visto": 0},
    {"id": 86, "grupo": "Semifinal", "local": "Ganador Cuartos 3", "visitante": "Ganador Cuartos 4", "fecha": "14 Julio", "hora": "14:00", "estadio": "Estadio BBVA", "visto": 0},
    # TERCER PUESTO (id 87)
    {"id": 87, "grupo": "Tercer Puesto", "local": "Perdedor Semifinal 1", "visitante": "Perdedor Semifinal 2", "fecha": "17 Julio", "hora": "15:00", "estadio": "Estadio Akron", "visto": 0},
    # FINAL (id 88)
    {"id": 88, "grupo": "Final", "local": "Ganador Semifinal 1", "visitante": "Ganador Semifinal 2", "fecha": "18 Julio", "hora": "17:00", "estadio": "Estadio Azteca", "visto": 0},]